FROM registry.opensuse.org/opensuse/distrobox

RUN zypper --non-interactive install \
    # Needed to do helix -g build
    gcc-c++ \
    helix bat git-delta xclip \
    wezterm lua-language-server \
    direnv \
    gopass \
    ripgrep fd gawk \
    just \
    pueue \
    broot \
    starship

# Share some commands with host
RUN ln -fs /usr/bin/distrobox-host-exec /usr/bin/podman
RUN ln -fs /usr/bin/distrobox-host-exec /usr/bin/distrobox
RUN ln -fs /usr/bin/distrobox-host-exec /usr/bin/flatpak
