build-blingbase:
    podman build -t blingbase .

# Run this as your first command
create-blingbox: build-blingbase 
    distrobox assemble create
    distrobox enter bling_base -- distrobox-export --app wezterm

# Make initial setup
init-blingbox:
    helix -g fetch
    helix -g build
    
remove-blingbox: 
    distrobox assemble rm
